# Generated by Django 3.2 on 2021-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_registration_mark', models.CharField(max_length=100)),
                ('vehicle_make_and_model', models.CharField(max_length=100)),
                ('mileage_in_kilometers', models.IntegerField()),
                ('date_of_last_technical_inspection', models.DateField()),
            ],
        ),
    ]
